######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 28 22:31:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . .. /usr/local/include/clang-c
QMAKE_CXX = clang
QMAKE_LINK = clang
config += debug

LIBS += -L/usr/local/lib -lclang


# Input
HEADERS += \
    QObjectIndexer.h \
    ../ClangUtil.h \
    ../SourceIndex.h

FORMS += \
    MainWindow.ui

SOURCES += \
    main.cpp \
    QObjectIndexer.cpp \
    ../ClangUtil.cpp \
    ../SourceIndex.cpp
