######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 25 20:12:15 2014
######################################################################

TEMPLATE = lib
CONFIG += static
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/include/clang-c
QMAKE_CXX = clang

# Input
HEADERS += ClangUtil.h SourceIndex.h
SOURCES += ClangUtil.cpp SourceIndex.cpp
