######################################################################
# Automatically generated by qmake (3.0) Fri Apr 12 09:55:03 2013
######################################################################

TEMPLATE = app
TARGET = exampleSrc
INCLUDEPATH += .

# Input
HEADERS += Counter.h
SOURCES += Counter.cpp main.cpp
